

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8082:8082"
    environment:
      - CONFIG_PATH=./local.yaml
    volumes:
      - ./backend/auth/internal/config:/app/config
      - auth_data:/app/data
    networks:
      - app-network

  task:
    build:
      context: .
      dockerfile: Dockerfile.task
    ports:
      - "8081:8081"
    environment:
      - CONFIG_PATH=./local.yaml
    volumes:
      - ./backend/task/internal/config:/app/config
      - task_data:/app/data
    networks:
      - app-network
    depends_on:
      - auth

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    networks:
      - app-network
    depends_on:
      - auth
      - task

volumes:
  auth_data:
  task_data:

networks:
  app-network:
    driver: bridge
